/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Asessment1DFSBFS;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        Node start = new Node("Start",2);
        
        start.createChildren(3, 2, 11, start); //recursive function to generate a tree (depth, width/number of children, number of the target node, startnode)

        DFS dfs = new DFS();
        System.out.println(dfs.getTarget(start).getData() + "DFS");

        BFS bfs = new BFS();
        
        ArrayList<Node> begin  = new ArrayList<>();
        begin.add(start);

        Node node = bfs.getTarget(begin);
        System.out.println(node.getData() + "BFS");

    }
}
